dimensions: fix visit_group_join
so that each visit may only appear once. Otherwise the pipelines
see multiple visit_groups for a particular visit, and attempt
to generate calexps multiple times for the same data and fail
with the error:
    ValueError: Only one node is allowed to produce calexp@...