skyLines: remove non-ASCII chars
Some non-ASCII characters got into the O2 descriptions, which
breaks ArcLineSet.writeFits:
UnicodeEncodeError: 'ascii' codec can't encode character '\u2206' in position 3: ordinal not in range(128)

Replaced the non-ASCII characters with ASCII representations.